name: test d01

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ex: ["00", "01"]

    steps:
      - uses: actions/checkout@v3
      - name: make d01 ex${{ matrix.ex }}
        run: make -C ./exercise/d01/ex${{ matrix.ex }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ex: ["00", "01"]

    steps:
      - uses: actions/checkout@v3
      - name: test d01 ex${{ matrix.ex }}
        run: make -C ./exercise/d01/ex${{ matrix.ex }} test

  norminette:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ex: ["00", "01"]

    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: "./exercise/d01/ex${{ matrix.ex }}"
