name: test d03

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ex: ["00", "01", "02", "03", "04"]

    steps:
      - uses: actions/checkout@v3
      - name: make d03 ex${{ matrix.ex }}
        run: make -C ./src/d03/ex${{ matrix.ex }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ex: ["00", "01", "02", "03", "04"]

    steps:
      - uses: actions/checkout@v3
      - name: test d03 ex${{ matrix.ex }}
        run: make -C ./src/d03/ex${{ matrix.ex }} test

  norminette:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ex: ["00", "01", "02", "03", "04"]

    steps:
      - uses: actions/checkout@v2
      - uses: alexandregv/norminette-action@v3
        with:
          flags: "./src/d03/ex${{ matrix.ex }}"
